# Generated by Django 4.2.5 on 2024-02-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentfiles', '0002_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, max_length=399, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=399, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=399, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=399, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=399, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parents_contact_no',
            field=models.CharField(blank=True, max_length=399, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='usn',
            field=models.CharField(blank=True, max_length=399, null=True, unique=True),
        ),
    ]
