# Generated by Django 4.2.5 on 2024-02-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentfiles', '0005_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='D.O.B'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=399, null=True, verbose_name='Email ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=399, null=True, verbose_name='Student First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=399, null=True, verbose_name='Student Last Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_no',
            field=models.CharField(max_length=399, null=True, verbose_name='Mobile No'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parents_contact_no',
            field=models.CharField(max_length=399, null=True, verbose_name='Parents Contact No'),
        ),
        migrations.AlterField(
            model_name='student',
            name='usn',
            field=models.CharField(max_length=399, null=True, unique=True, verbose_name='Student USN'),
        ),
    ]
