# Generated by Django 4.2.5 on 2024-02-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentfiles', '0006_alter_student_dob_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exam_fees_paid',
            field=models.CharField(max_length=399, null=True, verbose_name='Exam Fess Paid'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Date'),
        ),
    ]
